# Generated by Django 5.2 on 2025-11-30 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household_budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeAndExpenditureRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('comment', models.TextField(blank=True)),
                ('log_time', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='household_budget.categories')),
            ],
        ),
    ]
