# Generated by Django 5.2 on 2025-12-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household_budget', '0002_incomeandexpenditurerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeandexpenditurerecord',
            name='place',
            field=models.TextField(default=''),
        ),
    ]
